export interface ExerciseSeed {
  name: string;
  category: 'chest' | 'back' | 'legs' | 'shoulders' | 'arms' | 'core' | 'cardio';
  equipment: 'barbell' | 'dumbbell' | 'machine' | 'bodyweight' | 'cable' | 'kettlebell' | 'other';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  muscleGroups: string[];
  instructions?: string;
}

export const exerciseSeedData: ExerciseSeed[] = [
  // === CHEST (8 exercises) ===
  {
    name: 'Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['chest', 'triceps', 'front delts'],
    instructions: 'Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up.',
  },
  {
    name: 'Incline Dumbbell Press',
    category: 'chest',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    muscleGroups: ['upper chest', 'triceps', 'front delts'],
    instructions: 'Set bench to 30-45 degrees, press dumbbells up from shoulder level.',
  },
  {
    name: 'Dumbbell Fly',
    category: 'chest',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['chest'],
    instructions: 'Lie flat, arms extended, lower dumbbells in arc motion, squeeze chest at top.',
  },
  {
    name: 'Push-Up',
    category: 'chest',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'triceps', 'front delts', 'core'],
    instructions: 'Hands shoulder-width, lower chest to floor, push back up.',
  },
  {
    name: 'Cable Crossover',
    category: 'chest',
    equipment: 'cable',
    difficulty: 'intermediate',
    muscleGroups: ['chest'],
    instructions: 'Set cables high, step forward, bring handles together in front of chest.',
  },
  {
    name: 'Decline Bench Press',
    category: 'chest',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['lower chest', 'triceps'],
    instructions: 'Bench at decline angle, press barbell from lower chest.',
  },
  {
    name: 'Chest Dip',
    category: 'chest',
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    muscleGroups: ['lower chest', 'triceps', 'front delts'],
    instructions: 'Lean forward on dip bars, lower until stretch in chest, push up.',
  },
  {
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['chest', 'triceps'],
    instructions: 'Adjust seat height, press handles forward, control the return.',
  },

  // === BACK (8 exercises) ===
  {
    name: 'Barbell Row',
    category: 'back',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['lats', 'rhomboids', 'biceps', 'rear delts'],
    instructions: 'Hinge at hips, pull bar to lower chest, squeeze shoulder blades.',
  },
  {
    name: 'Pull-Up',
    category: 'back',
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    muscleGroups: ['lats', 'biceps', 'rear delts'],
    instructions: 'Hang from bar, pull chest to bar, lower with control.',
  },
  {
    name: 'Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    muscleGroups: ['lats', 'biceps'],
    instructions: 'Pull bar to upper chest, squeeze lats, control return.',
  },
  {
    name: 'Seated Cable Row',
    category: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    muscleGroups: ['lats', 'rhomboids', 'biceps'],
    instructions: 'Sit upright, pull handle to stomach, squeeze shoulder blades.',
  },
  {
    name: 'Dumbbell Row',
    category: 'back',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['lats', 'rhomboids', 'biceps'],
    instructions: 'One hand on bench, row dumbbell to hip, squeeze lat.',
  },
  {
    name: 'Deadlift',
    category: 'back',
    equipment: 'barbell',
    difficulty: 'advanced',
    muscleGroups: ['lower back', 'glutes', 'hamstrings', 'traps'],
    instructions: 'Feet hip-width, hinge to grip bar, drive through heels, stand tall.',
  },
  {
    name: 'T-Bar Row',
    category: 'back',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['lats', 'rhomboids', 'biceps'],
    instructions: 'Straddle bar, row to chest using close grip handle.',
  },
  {
    name: 'Face Pull',
    category: 'back',
    equipment: 'cable',
    difficulty: 'beginner',
    muscleGroups: ['rear delts', 'rhomboids', 'rotator cuff'],
    instructions: 'Pull rope to face, externally rotate at end, squeeze rear delts.',
  },

  // === LEGS (10 exercises) ===
  {
    name: 'Barbell Squat',
    category: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['quads', 'glutes', 'hamstrings', 'core'],
    instructions: 'Bar on upper back, squat until thighs parallel, drive up through heels.',
  },
  {
    name: 'Romanian Deadlift',
    category: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['hamstrings', 'glutes', 'lower back'],
    instructions: 'Slight knee bend, hinge at hips, lower bar along legs, feel hamstring stretch.',
  },
  {
    name: 'Leg Press',
    category: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes'],
    instructions: 'Feet shoulder-width on platform, lower until 90 degrees, press up.',
  },
  {
    name: 'Leg Curl',
    category: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['hamstrings'],
    instructions: 'Lie face down, curl weight toward glutes, control return.',
  },
  {
    name: 'Leg Extension',
    category: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['quads'],
    instructions: 'Sit upright, extend legs fully, squeeze quads, lower with control.',
  },
  {
    name: 'Bulgarian Split Squat',
    category: 'legs',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    muscleGroups: ['quads', 'glutes'],
    instructions: 'Rear foot on bench, lower until front thigh parallel, drive up.',
  },
  {
    name: 'Walking Lunge',
    category: 'legs',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'hamstrings'],
    instructions: 'Step forward into lunge, drive through front heel, alternate legs.',
  },
  {
    name: 'Calf Raise',
    category: 'legs',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['calves'],
    instructions: 'Stand on edge of platform, raise heels high, lower for stretch.',
  },
  {
    name: 'Goblet Squat',
    category: 'legs',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['quads', 'glutes', 'core'],
    instructions: 'Hold dumbbell at chest, squat deep, keep torso upright.',
  },
  {
    name: 'Hip Thrust',
    category: 'legs',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['glutes', 'hamstrings'],
    instructions: 'Upper back on bench, bar over hips, drive hips up, squeeze glutes.',
  },

  // === SHOULDERS (7 exercises) ===
  {
    name: 'Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['front delts', 'side delts', 'triceps'],
    instructions: 'Bar at shoulder level, press overhead, lower with control.',
  },
  {
    name: 'Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['side delts'],
    instructions: 'Slight bend in elbows, raise arms to sides until parallel, lower slowly.',
  },
  {
    name: 'Dumbbell Front Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['front delts'],
    instructions: 'Arms straight, raise dumbbells in front to shoulder height.',
  },
  {
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    muscleGroups: ['front delts', 'side delts'],
    instructions: 'Start palms facing you, rotate as you press overhead.',
  },
  {
    name: 'Reverse Fly',
    category: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['rear delts', 'rhomboids'],
    instructions: 'Bend over, raise arms to sides, squeeze rear delts.',
  },
  {
    name: 'Upright Row',
    category: 'shoulders',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['side delts', 'traps'],
    instructions: 'Pull bar up along body to chin height, elbows lead.',
  },
  {
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['front delts', 'side delts', 'triceps'],
    instructions: 'Seated or standing, press dumbbells overhead, lower to shoulders.',
  },

  // === ARMS (10 exercises) ===
  {
    name: 'Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    difficulty: 'beginner',
    muscleGroups: ['biceps'],
    instructions: 'Elbows at sides, curl bar up, squeeze biceps, lower with control.',
  },
  {
    name: 'Dumbbell Curl',
    category: 'arms',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['biceps'],
    instructions: 'Alternate or together, curl with supinated grip, control descent.',
  },
  {
    name: 'Hammer Curl',
    category: 'arms',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['biceps', 'brachialis'],
    instructions: 'Neutral grip, curl dumbbells up, keep elbows stationary.',
  },
  {
    name: 'Preacher Curl',
    category: 'arms',
    equipment: 'dumbbell',
    difficulty: 'intermediate',
    muscleGroups: ['biceps'],
    instructions: 'Arms on preacher bench, curl weight up, full stretch at bottom.',
  },
  {
    name: 'Tricep Pushdown',
    category: 'arms',
    equipment: 'cable',
    difficulty: 'beginner',
    muscleGroups: ['triceps'],
    instructions: 'Elbows at sides, push bar down until arms straight, squeeze triceps.',
  },
  {
    name: 'Skull Crusher',
    category: 'arms',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['triceps'],
    instructions: 'Lie flat, lower bar to forehead, extend arms, keep elbows in.',
  },
  {
    name: 'Overhead Tricep Extension',
    category: 'arms',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['triceps'],
    instructions: 'Hold dumbbell overhead, lower behind head, extend up.',
  },
  {
    name: 'Close-Grip Bench Press',
    category: 'arms',
    equipment: 'barbell',
    difficulty: 'intermediate',
    muscleGroups: ['triceps', 'chest'],
    instructions: 'Hands shoulder-width, lower bar to chest, press up.',
  },
  {
    name: 'Concentration Curl',
    category: 'arms',
    equipment: 'dumbbell',
    difficulty: 'beginner',
    muscleGroups: ['biceps'],
    instructions: 'Elbow on inner thigh, curl dumbbell, squeeze at top.',
  },
  {
    name: 'Tricep Dip',
    category: 'arms',
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    muscleGroups: ['triceps', 'chest'],
    instructions: 'On parallel bars or bench, lower body, press up.',
  },

  // === CORE (5 exercises) ===
  {
    name: 'Plank',
    category: 'core',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    muscleGroups: ['abs', 'obliques', 'lower back'],
    instructions: 'Forearms on ground, body straight, hold position.',
  },
  {
    name: 'Hanging Leg Raise',
    category: 'core',
    equipment: 'bodyweight',
    difficulty: 'intermediate',
    muscleGroups: ['lower abs', 'hip flexors'],
    instructions: 'Hang from bar, raise legs to parallel or higher, lower with control.',
  },
  {
    name: 'Cable Crunch',
    category: 'core',
    equipment: 'cable',
    difficulty: 'beginner',
    muscleGroups: ['abs'],
    instructions: 'Kneel facing cable, crunch down bringing elbows to knees.',
  },
  {
    name: 'Russian Twist',
    category: 'core',
    equipment: 'bodyweight',
    difficulty: 'beginner',
    muscleGroups: ['obliques', 'abs'],
    instructions: 'Seated, lean back, rotate torso side to side.',
  },
  {
    name: 'Ab Wheel Rollout',
    category: 'core',
    equipment: 'other',
    difficulty: 'advanced',
    muscleGroups: ['abs', 'lats', 'shoulders'],
    instructions: 'Kneel, roll wheel forward, extend body, roll back.',
  },

  // === CARDIO (2 exercises for tracking) ===
  {
    name: 'Treadmill Running',
    category: 'cardio',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['legs', 'cardiovascular'],
    instructions: 'Track duration, distance, and average pace.',
  },
  {
    name: 'Rowing Machine',
    category: 'cardio',
    equipment: 'machine',
    difficulty: 'beginner',
    muscleGroups: ['back', 'legs', 'cardiovascular'],
    instructions: 'Track duration, distance, and split time.',
  },
];
